### ISSUE TITLE
Optimization of compiler flags

### ISSUE THREAD

**Issue by KarunDatadien** [wur-wsg/VIC#22]
When encountering "variable multiply defined" type compilation errors, this may be due to the default behavior of gcc10+ having changed from older gcc versions. Adding the `-fcommon` flag to the 'CFLAGS' variable in the Makefile removes the compilation error by reverting to the default behavior of older gcc versions.

For optimization flags I looked at the performance of the following 3: `-O0` (no optimization), `-O3` and the more aggressive `-Ofast`. (Details here: https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html)

I checked the output files for O0 and O3 to be bitwise identical. Not the case for `-Ofast`, which aggressively optimizes floating-point arithmetic, likely leading to loss of precision. So it should be used cautiously.

### Performance Comparison (average time calculated from 3 runs for each flag)

| Optimization Level | Avg Runtime      | Avg Write-Time    |
|-------------------- |------------------|-------------------|
| -O0                | 38.9464          | 0.740519667      |
| -O3                | 22.92196667      | 0.694949         |
| -Ofast             | 19.02596667      | 0.635875667      |

**'-O3' reduces runtime by 41%
'-O3' reduces write-time by  6.15%**

Profiling data: 
[compilation_flags_profiling.xlsx](https://github.com/wur-wsg/VIC/files/14166853/compilation_flags_profiling.xlsx)

**Comment by nauta008** [comment]
Develop and master branches has been updated. Issue can be closed.
